# Generated by Django 3.1.2 on 2020-10-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20201010_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'профиль', 'verbose_name_plural': 'профили'},
        ),
        migrations.AddField(
            model_name='profile',
            name='is_dispatcher',
            field=models.BooleanField(default=False, help_text='Является ли пользователь диспетчером?', verbose_name='Диспетчер'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_rso_user',
            field=models.BooleanField(default=False, help_text='Относится ли пользователь к РСО?', verbose_name='Пользователь РСО'),
        ),
    ]
