# Generated by Django 3.1.2 on 2020-10-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20201010_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Communications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.communicationstype', verbose_name='Объект коммуникаций')),
            ],
        ),
    ]
