# Generated by Django 3.1.2 on 2020-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20201010_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тип инцидента')),
            ],
            options={
                'verbose_name': 'тип инцидента',
                'verbose_name_plural': 'типы инцидентов',
            },
        ),
        migrations.AlterField(
            model_name='communications',
            name='parameters',
            field=models.CharField(blank=True, max_length=250, verbose_name='Параметры объекта'),
        ),
    ]
