# Generated by Django 3.1.2 on 2020-10-10 15:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20201010_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2020, 10, 10, 18, 52, 55, 857976))),
                ('end_date', models.DateTimeField(blank=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.communicationstype', verbose_name='Объект коммуникаций')),
            ],
        ),
    ]
