# Generated by Django 3.1.2 on 2020-10-10 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'verbose_name': 'инцидент', 'verbose_name_plural': 'инциденты'},
        ),
        migrations.AddField(
            model_name='incident',
            name='additional_info',
            field=models.CharField(blank=True, max_length=250, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 18, 54, 48, 138632)),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.communicationstype', verbose_name='Инцидент'),
        ),
    ]
