# Generated by Django 3.1.2 on 2020-10-10 15:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_auto_20201010_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 18, 55, 59, 835144)),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.incidenttype', verbose_name='Инцидент'),
        ),
    ]
