# Generated by Django 3.1.2 on 2020-10-10 15:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_auto_20201010_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communications',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.communicationstype', verbose_name='Тип объекта коммуникаций'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='end_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 18, 57, 18, 349826), verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.incidenttype', verbose_name='Тип инцидента'),
        ),
    ]
