# Generated by Django 3.1.2 on 2020-10-10 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_auto_20201010_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время завершения'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 0, 27, 704338), verbose_name='Дата и время начала'),
        ),
    ]
