# Generated by Django 3.1.2 on 2020-10-10 16:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20201010_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='communications_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.communications', verbose_name='Объект коммуникаций, на котором инцидент'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 10, 19, 5, 14, 517742), verbose_name='Дата и время начала'),
        ),
    ]
